### ISSUE TITLE
Make focus work across xprocspec files

### ISSUE THREAD

**Issue by bertfrees** [daisy/xprocspec#37]
It would be awesome if by temporarily adding a focus attribute on a scenario in one file I could disable not only all other scenarios in that file but also in all other files. I often find myself deleting xprocspec files in order to make testing faster.

It would be even cooler if focus would work across xprocspec AND xspec files, but I realize that's probably asking for too much :)

**Comment by josteinaj** [comment]
Yes, totally agree! I'm doing the same thing (renaming/moving xprocspec files).

Making it work across files would be a thing for [xproc-maven-plugin](https://github.com/daisy/xproc-maven-plugin) though, wouldn't it? xprocspec is not aware of any other files than the current one.

**Comment by bertfrees** [comment]
The maven-plugin doesn't parse the files so I thought maybe xprocspec could allow a sequence as input?

**Comment by josteinaj** [comment]
Yeah I guess we can do it that way. Might be better indeed.

**Comment by josteinaj** [comment]
Replaced by #42
