### ISSUE TITLE
Make xfail work on x:scenario elements

### ISSUE THREAD

**Issue by bertfrees** [daisy/xprocspec#40]
If a test throws an error which is an expected failure, the test currently fails even if the xfail attribute is used.

Putting the attribute on an "errors" x:expect works:

``` xml
<x:context label="errors">
  <x:document type="errors"/>
</x:context>
<x:expect type="count" label="the step should execute successfully without throwing any errors" max="0" xfail="true"/>
```

but only if the `x:expect` with the actual comparison is removed which is unpractical.

**Comment by josteinaj** [comment]
I'm not sure I understand the problem. Does your example above not work?

When `<x:document type="errors"/>` is not tested explicitly in a scenario, a test for it will be automatically inserted to check that no errors are thrown and that the scenario executes successfully. If the step is actually expected to throw an error, you need to do as in your example.

**Comment by bertfrees** [comment]
The step is not supposed to throw an error, but it does. It is an expected failure.

**Comment by bertfrees** [comment]
The example above works, but I shouldn't have to remove to x:expect that verifies the result port. Currently I have to remove it because there is no document on the result port because there was an error.

**Comment by josteinaj** [comment]
So what you want is that when an `@xfail` appears on a `<x:expect>` that checks the error port, then all other `<x:expect>` elements in that particular scenario should be skipped so that they do not fail?

**Comment by bertfrees** [comment]
No I was more thinking about just making the `@xfail` work on `x:scenario`. But it was actually more a question, I'm not sure what the best approach is.

**Comment by bertfrees** [comment]
In other words `@xfail` on `x:scenario` could mean that at least one `x:expect` must fail, and errors would be treated at failures.

**Comment by josteinaj** [comment]
Ok, yeah I think that makes sense.
