### ISSUE TITLE
focus on x:description?

### ISSUE THREAD

**Issue by bertfrees** [daisy/xprocspec#45]
Now that in xproc-maven-plugin I have made focus work across files (see also https://github.com/daisy/xprocspec/issues/37), maybe it would make sense on x:description?

**Comment by josteinaj** [comment]
Yes. In the context of multiple files, the x:description element is semantically similar to a x:scenario.

**Comment by bertfrees** [comment]
See PR: https://github.com/daisy/xprocspec/pull/48
