### ISSUE TITLE
Add an argument ordered="true|false" on x:document type="zip"

### ISSUE THREAD

**Issue by bertfrees** [daisy/xprocspec#61]
Because in most cases you are not interested in the ordering of ZIP entries.

**Comment by bertfrees** [comment]
@josteinaj I'm going to try to implement this now.

**Comment by bertfrees** [comment]
See PR: https://github.com/daisy/xprocspec/pull/63

**Comment by josteinaj** [comment]
Fixed in #63 / #64.
