### ISSUE TITLE
xfail

### ISSUE THREAD

**Issue by bertfrees** [daisy/xprocspec#7]
Besides focus and pending,  an attribute to mark known failures, similar to Automake's xfail (https://www.gnu.org/software/automake/manual/html_node/Scripts_002dbased-Testsuites.html).

I currently mark known failures with pending (which means "Completely skip this scenario"), but xfail would be more appropriate. It means "This scenario MUST fail".

**Comment by bertfrees** [comment]
Maybe xfail should resemble pending more, i.e. the value can be a comment?

**Comment by josteinaj** [comment]
Good idea. Added as #34
